[package]
name = "tarindex"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tarindex"
path = "src/bin/tarindex.rs"

[dependencies]
tar = "0.4"
zerocopy = "0.6.1"
tarfs-defs = { path = "../tarfs-defs" }
